<?php use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('homeheader'); ?>
<div id="page-container">
    <div class="section_" id="content-wrap">
        <div>
            <h1 style="text-align: center; width: 100% ">Scores Pessoais</h1>
            <div class="container" style="text-align: center">
                <div class="row">
                    <div class="col-md-4">
                        <h1>Jogos: 2</h1>
                    </div>
                    <div class="col-md-4">
                        <h1>Ganhos: 0</h1>
                    </div>
                    <div class="col-md-4">
                        <h1>Perdas: 2</h1>
                    </div>
                </div>
            </div>
        </div>
        <div style="margin: 15px;">
            <div class="table-responsive" style="width: 100%;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="panel panel-default panel-table">
                                <div class="panel-body">
                                    <table class="table table-striped table-bordered table-list">
                                        <thead>
                                        <tr>
                                            <th><em class="fa fa-cog"></em></th>
                                            <th class="hidden-xs">ID</th>
                                            <th>Score</th>
                                            <th>Data</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td align="center">
                                                <a class="btn btn-danger"><em class="fa fa-crosshairs"></em></a>
                                            </td>
                                            <td class="hidden-xs">1</td>
                                            <td>20</td>
                                            <td>2020-12-24</td>
                                        </tr>
                                        </tbody>
                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <?php Layout::includeLayout('footer'); ?>
</div>
