<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$users = Data::get('users');
Layout::includeLayout('homeheader'); ?>
<div id="page-container">
    <div class="section_" id="content-wrap">
        <div>
            <h1 style="text-align: center; width: 100% ">Gerir Bans</h1>
        </div>
        <div style="margin: 15px;">
            <div class="table-responsive" style="width: 100%;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="panel panel-default panel-table">
                                <div class="panel-body">
                                    <table class="table table-striped table-bordered table-list">
                                        <thead>
                                        <tr>
                                            <th><em class="fa fa-cog"></em>Ban</th>
                                            <th class="hidden-xs">ID</th>
                                            <th>Jogador</th>
                                            <th>Email</th>
                                            <th>Genero</th>
                                            <th>Accesso</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($users as &$row) {?>
                                            <tr class="click_categories"
                                                data-href='manage.php?id_category=<?=$row[0]?>'>
                                                <td align="center">
                                                    <a class="btn btn-danger"><em class="fa fa-crosshairs"></em></a>
                                                </td>
                                                <td><?= $row[0] ?></td>
                                                <td><?= $row[1] ?></td>
                                                <td><?= $row[4] ?></td>
                                                <td><?= $row[5] ?></td>
                                                <td><?= $row[7] ?></td>
                                            </tr>
                                        <?php }?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php Layout::includeLayout('footer');
    Tracy\Debugger::barDump($users)?>
</div>