<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('homeheader'); ?>
<div id="page-container">
    <div class="section_" id="content-wrap">
        <div>
            <h1 style="text-align: center; width: 100% ">Gerir Bans</h1>
        </div>
        <div style="margin: 15px;">
            <div class="table-responsive" style="width: 100%;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="panel panel-default panel-table">
                                <div class="panel-body">
                                    <table class="table table-striped table-bordered table-list">
                                        <thead>
                                        <tr>
                                            <th><em class="fa fa-cog"></em>Ban</th>
                                            <th class="hidden-xs">ID</th>
                                            <th>Jogador</th>
                                            <th>Email</th>
                                            <th>Genero</th>
                                            <th>Accesso</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach (User::all() as $user) { ?>
                                            <tr class="click_categories">
                                                <?php if ($user->bloqueado == 0) { ?>
                                                    <td align="center">
                                                        <a href="<?= URL::toRoute('user/ban', $user->id_user) ?>" class="btn btn-success">
                                                            <b>Block</b>
                                                        </a>
                                                    </td>
                                                <?php } else { ?>
                                                    <td align="center">
                                                        <a href="<?= URL::toRoute('user/ban', $user->id_user) ?>" class="btn btn-danger">
                                                            <b>Unblock</b>
                                                        </a>
                                                    </td>
                                                <?php } ?>
                                                <td><?= $user->id_user ?></td>
                                                <td><?= $user->nickname ?></td>
                                                <td><?= $user->email ?></td>
                                                <td><?= $user->acesso == 'M' ? 'Male' : 'Female' ?></td>
                                                <td><?= $user->acesso == 1 ? 'Administrador' : 'Jogador' ?></td>

                                            </tr>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php Layout::includeLayout('footer');
    Tracy\Debugger::barDump(Session::get('user')) ?>
</div>