<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$engine = Data::get('ge');
$user = Session::get('user');
/* @var GameEngine $engine */

Layout::includeLayout('homeheader'); ?>
<div id="page-container">
    <div class="section_" id="content-wrap">
        <div>
            <h1 style="text-align: center; width: 100% ">Jogo</h1>
            <?php
            if ($engine->getEstadoJogo() == 5) {
                if ($engine->tabuleiro->getVencedor() == 1) { ?>
                    <script>
                        var nickname = "<?=$user->nickname?>";
                        alert("Parabéns Ganhou!! " + nickname);
                    </script>
                <?php } else if ($engine->tabuleiro->getVencedor() == 2) { ?>
                    <script>
                        var nickname = "<?=$user->nickname?>";
                        alert("Ora bolas Perdeu!! " + nickname);
                    </script>
                <?php } else { ?>
                    <script>
                        alert("Parece que houve um empate!!");
                    </script>
                <?php }
            }

            ?>
            <div style="margin: 29px; text-align: left">
                <h1>Jogador - <?= $user->nickname ?></h1> <!-- TODO Nome do jogador -->
                <div>
                    <?php
                    if (Session::has('gameEngine') && $engine->getEstadoJogo() != 0) {
                        for ($i = 1; $i < 10; $i++) {
                            if (!$engine->tabuleiro->numeroBloqueioP1->getNumerosBloqueio($i) && ($engine->getEstadoJogo() >= 3 || $engine->getEstadoJogo() == 5)) { ?>
                                <button disabled class="btn " type="button"><?= $i ?></button>
                            <?php } else if ($engine->tabuleiro->numeroBloqueioP1->seletorNumeros->selectionHasNumber($i)) { ?>
                                <a href="<?= URL::toRoute('jogo/seleciona', $i) ?>">
                                    <button class="btn btn-success" type="button"><?= $i ?></button>
                                </a>

                            <?php } else if (!$engine->tabuleiro->numeroBloqueioP1->getNumerosBloqueio($i)) { ?>
                                <a href="<?= URL::toRoute('jogo/seleciona', $i) ?>">
                                    <button class="btn btn-default" type="button"><?= $i ?></button>
                                </a>
                            <?php }

                            if ($engine->tabuleiro->numeroBloqueioP1->getNumerosBloqueio($i)) { ?>
                                <button disabled class="btn btn-danger" type="button"><?= $i ?></button>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="text-center">
            <h1>A jogar:
                - <?php if ($engine->getEstadoJogo() == 1 || $engine->getEstadoJogo() == 2) echo $user->nickname; else if ($engine->getEstadoJogo() == 3 || $engine->getEstadoJogo() == 4) echo 'Guest' ?></h1>
            <div style="height: 100px">
                <h1 style="float: left;margin-left: 100px;font-size: 100px;width: 112px;margin-top: 0;"><?php if (Session::has('gameEngine') && $engine->getEstadoJogo() != 0) echo $engine->tabuleiro->numeroBloqueioP1->getFinalPointSum(); ?></h1>

                <?php if ($engine->getEstadoJogo() == 2 || $engine->getEstadoJogo() == 4) { ?>
                    <img src="<?= Asset::image($engine->tabuleiro->resultadoDado1 . '.png') ?>" width="112px"
                         style="margin-right: 15px;">
                    <img src="<?= Asset::image($engine->tabuleiro->resultadoDado2 . '.png') ?>" width="112px">
                <?php } ?>

                <h1 style="float: right;margin: 0;margin-right: 100px;width: 112px;font-size: 100px;"><?php if (Session::has('gameEngine') && $engine->getEstadoJogo() != 0) echo $engine->tabuleiro->numeroBloqueioP2->getFinalPointSum(); ?></h1>
            </div>
            <div style="text-align: center; width: 100%; ">
                <?php if ($engine->getEstadoJogo() == 1 || $engine->getEstadoJogo() == 3) { ?>
                    <a href="<?= URL::toRoute('jogo/rolardados') ?>">
                        <button class="btn btn-primary" type="button"
                                style=" margin-top: -110px; ">
                            Roll Dice
                        </button>
                    </a>
                <?php } ?>

                <?php if (!Session::has('gameEngine') || $engine->getEstadoJogo() == 5 || $engine->getEstadoJogo() == 0) { ?>
                    <a href="<?= Url::toRoute('jogo/iniciarjogo') ?>">
                        <button class="btn btn-primary" type="button"
                                style="  margin-top: -110px; ">
                            Iniciar Jogo
                        </button>
                    </a>
                <?php } ?>

            </div>


        </div>
        <div>
            <div>
                <div style="margin: 29px; text-align: right;">
                    <div>
                        <?php
                        if (Session::has('gameEngine') && $engine->getEstadoJogo() != 0) {
                            for ($i = 1; $i < 10; $i++) {
                                if (!$engine->tabuleiro->numeroBloqueioP2->getNumerosBloqueio($i) && ($engine->getEstadoJogo() < 3 || $engine->getEstadoJogo() == 5)) { ?>
                                    <button disabled class="btn " type="button"><?= $i ?></button>
                                <?php } else if ($engine->tabuleiro->numeroBloqueioP2->seletorNumeros->selectionHasNumber($i)) { ?>
                                    <a href="<?= URL::toRoute('jogo/seleciona', $i) ?>">
                                        <button class="btn btn-success" type="button"><?= $i ?></button>
                                    </a>

                                <?php } else if (!$engine->tabuleiro->numeroBloqueioP2->getNumerosBloqueio($i)) { ?>
                                    <a href="<?= URL::toRoute('jogo/seleciona', $i) ?>">
                                        <button class="btn btn-default" type="button"><?= $i ?></button>
                                    </a>
                                <?php }

                                if ($engine->tabuleiro->numeroBloqueioP2->getNumerosBloqueio($i)) { ?>
                                    <button disabled class="btn btn-danger" type="button"><?= $i ?></button>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>

                    </div>
                    <h1>Jogador - Guest</h1>
                </div>
            </div>
        </div>
    </div>
    <?php Layout::includeLayout('footer');
    Tracy\Debugger::barDump($engine);
    ?>
</div>