<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;

$user = Session::get('user');
Layout::includeLayout('homeheader');
$scores = Data::get('scores');
$games = Score::count(array('conditions' => 'user=' . $user->id_user));
$lost = Score::count(array('conditions' => 'user=' . $user->id_user . ' and state like \'Lost\''));
$win = Score::count(array('conditions' => 'user=' . $user->id_user . ' and state like \'Win\''));
$tie = Score::count(array('conditions' => 'user=' . $user->id_user . ' and state like \'Tie\''));
?>
<div id="page-container">
    <div class="section_" id="content-wrap">
        <div>
            <h1 style="text-align: center; width: 100% ">Scores Pessoais</h1>
            <div class="container" style="text-align: center">
                <div class="row">
                    <table class="table " style="text-align: center;">
                        <thead>
                        <tr style="text-align: center;">
                            <th style="text-align: center;">Jogos:</th>
                            <th style="text-align: center;">Ganhos:</th>
                            <th style="text-align: center;">Perdas:</th>
                            <th style="text-align: center;">Empates:</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td style="text-align: center;"> <?= $games ?></td>
                            <td style="text-align: center;"> <?= $win ?></td>
                            <td style="text-align: center;"> <?= $lost ?></td>
                            <td style="text-align: center;"> <?= $tie ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div style="margin: 15px;">
            <div class="table-responsive" style="width: 100%;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="panel panel-default panel-table">
                                <div class="panel-body">
                                    <table class="table table-striped table-bordered table-list">
                                        <thead>
                                        <tr>
                                            <th>Score</th>
                                            <th>State</th>
                                            <th>Data</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($scores as &$row) { ?>
                                            <tr>
                                                <td><?= $row->score ?></td>
                                                <td><?= $row->state ?></td>
                                                <td><?= $row->data->format('d-m-Y H:i') ?></td>
                                            </tr>
                                        <?php } ?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <?php Layout::includeLayout('footer');
    Tracy\Debugger::barDump($scores); ?>
</div>
