<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
$user = Session::get('user');
Layout::includeLayout('homeheader');
$scores = Data::get('scores');
$games = Score::count(array('conditions'=> 'user='.$user->id_user));
$lost = Score::count(array('conditions'=> 'user='.$user->id_user. ' and state like \'Lost\''));
$win = Score::count(array('conditions'=> 'user='.$user->id_user. ' and state like \'Win\''));
?>
<div id="page-container">
    <div class="section_" id="content-wrap">
        <div>
            <h1 style="text-align: center; width: 100% ">Scores Pessoais</h1>
            <div class="container" style="text-align: center">
                <div class="row">
                    <div class="col-md-4">
                        <h1>Jogos: <?=$games ?></h1>
                    </div>
                    <div class="col-md-4">
                        <h1>Ganhos: <?=$win ?></h1>
                    </div>
                    <div class="col-md-4">
                        <h1>Perdas: <?=$lost ?></h1>
                    </div>
                </div>
            </div>
        </div>
        <div style="margin: 15px;">
            <div class="table-responsive" style="width: 100%;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="panel panel-default panel-table">
                                <div class="panel-body">
                                    <table class="table table-striped table-bordered table-list">
                                        <thead>
                                        <tr>
                                            <th>Score</th>
                                            <th>State</th>
                                            <th>Data</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($scores as &$row) {?>
                                            <tr>
                                                <td><?= $row->score ?></td>
                                                <td><?= $row->state?></td>
                                                <td><?= $row->data->format('d-m-Y H:i') ?></td>
                                            </tr>
                                        <?php }?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <?php Layout::includeLayout('footer');
    Tracy\Debugger::barDump($scores);?>
</div>
