<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$scores = Data::get('scores');

Layout::includeLayout('homeheader'); ?>
<div id="page-container">
    <div class="section_" id="content-wrap">
        <div>
            <h1 style="text-align: center; width: 100% ">Top 10</h1>
        </div>
        <div style="margin: 15px;">
            <div class="table-responsive" style="width: 100%;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="panel panel-default panel-table">
                                <div class="panel-body">
                                    <table class="table table-striped table-bordered table-list">
                                        <thead>
                                        <tr>
                                            <th>Jogador</th>
                                            <th>Score</th>
                                            <th>State</th>
                                            <th>Data</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                       <?php
                                       foreach ($scores as &$row) {
                                           $user = User::find($row->user);?>
                                            <tr>
                                                <td><?= $user->nickname ?></td>
                                                <td><?= $row->score ?></td>
                                                <td><?= $row->state ?></td>
                                                <td><?= $row->data->format('d-m-Y H:i') ?></td>
                                            </tr>
                                        <?php }?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php Layout::includeLayout('footer');
    Tracy\Debugger::barDump($scores);?>
</div>