<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$msg = Data::get('msg');
Layout::includeLayout('header') ?>

    <!-- container -->
    <div class="container">
        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Sign in</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 section_" style="margin-top: 0px">
                    <div class="panel panel-default " style="background-color: transparent; border: none">
                        <p style="color: white; width: 100%; text-align: center;"><?= $msg->msg ?></p>
                        <div class="panel-body" style="color: black">
                            <h1 class="thin text-center" >Sign in to your account</h1>
                            <p class="text-center text-muted" style="color: white">Lorem ipsum dolor sit amet, <a style="color: black" href="<?= Url::toRoute('user/register')?>">Register</a> adipisicing elit. Quo nulla quibusdam cum doloremque incidunt nemo sunt a tenetur omnis odio. </p>
                            <hr>

                            <form id="login" action="<?= Url::toRoute('user/login') ?>" method="post">
                                <div class="top-margin">
                                    <label for="email">E-mail <span class="text-danger">*</span></label>
                                    <input id="email" name="email" type="text" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label for="password">Password <span class="text-danger">*</span></label>
                                    <input id="password" name="password" type="password" class="form-control">
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-8">
                                        <b><a style="color: black" href="">Forgot password?</a></b>
                                    </div>
                                    <div class="col-lg-4 text-right">
                                        <button class="btn btn-action" type="submit">Sign in</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>