<?php

use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
$user = Session::get('user');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Silvio Priem Mendes, PhD">

    <title>Shut the Box</title>

    <?= AssetBundler::css() ?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png') ?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css') ?>" media="screen">
    <link rel="stylesheet" href="<?= Asset::css('/perfil.css') ?>" media="screen">
    <link rel="stylesheet" href="<?= Asset::css('/table.css') ?>" media="screen">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js') ?>"></script>
    <script src="<?= Asset::js('respond.min.js') ?>"></script>
    <![endif]-->
</head>

<body class="home">
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom">
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= URL::toRoute('home/index') ?>">
               <!-- <img src="<?/*= Asset::image('logo.png') */?>" alt="WEBlogic MVC">-->
                Shut the Box
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li class="">
                    <a href="<?= URL::toRoute('home/home') ?>">Home</a>
                </li>
                <li>
                    <a href="<?= URL::toRoute('home/scores') ?>">Scores</a>
                </li>
                <li>
                    <a href="<?= URL::toRoute('home/top_10') ?>">TOP 10</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$user[1] ?>
                        <b class="caret"> </b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="active">
                            <a href="<?= Url::toRoute('home/perfil') ?>">Perfil</a>
                        </li>
                        <li class="active">
                            <a href="<?= Url::toRoute('home/ban') ?>">Gerir Bans</a>
                        </li>
                        <li>
                            <a href="<?= Url::toRoute('user/logout') ?>">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->